-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 19:19:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fypdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fypdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fypdatabase` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fypdatabase` ;

-- -----------------------------------------------------
-- Table `fypdatabase`.`batch_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`batch_modules` (
  `batch_name` CHAR(30) NOT NULL,
  `module_code` VARCHAR(6) NOT NULL,
  `batchmodID` INT NOT NULL AUTO_INCREMENT,
  `batchid` INT NOT NULL,
  PRIMARY KEY (`batchmodID`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`batches` (
  `batch_name` CHAR(30) NOT NULL,
  `no_students` INT NOT NULL,
  `batchid` INT NOT NULL,
  PRIMARY KEY (`batchid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`constraints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`constraints` (
  `costToExtendDays` INT NULL DEFAULT NULL,
  `costToExtendHours` INT NULL DEFAULT NULL,
  `costToHire` INT NULL DEFAULT NULL,
  `intervalBetweenSlots` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`lec_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`lec_modules` (
  `lec_id` VARCHAR(200) NOT NULL,
  `module_code` VARCHAR(45) NOT NULL,
  `modLecID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`modLecID`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`lecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`lecturers` (
  `lec_id` VARCHAR(300) NOT NULL,
  `lec_name` VARCHAR(200) NOT NULL,
  `max_hours` INT NOT NULL,
  `pay_rate` INT NULL DEFAULT NULL,
  PRIMARY KEY (`lec_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`master_tt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`master_tt` (
  `batch` VARCHAR(45) NULL DEFAULT NULL,
  `module` VARCHAR(45) NULL DEFAULT NULL,
  `lecturer` VARCHAR(45) NULL DEFAULT NULL,
  `hour` VARCHAR(45) NULL DEFAULT NULL,
  `day` VARCHAR(45) NULL DEFAULT NULL,
  `classroom` VARCHAR(45) NULL DEFAULT NULL,
  `slot_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`slot_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1668
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fypdatabase`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fypdatabase`.`module` (
  `mod_code` VARCHAR(50) NOT NULL,
  `mod_name` VARCHAR(50) NOT NULL,
  `credits` INT NOT NULL,
  PRIMARY KEY (`mod_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
